import { describe, it, expect } from "vitest";
import { bls12_381 } from "@noble/curves/bls12-381.js";
import { sha256 } from "@noble/hashes/sha2.js";
import {
  KONTOR_BLS_DST,
  deriveBlsKey,
  deriveMasterSK,
  getPublicKey,
  schnorrBindingHash,
  sign,
  signBlsBinding,
} from "../bls-primitives";
import { bytesToHex, hexToBytes } from "../postcard";

/**
 * Reference vectors generated by running `Horizon-Wallet/tool/bls-entry.js`
 * against the same fixed inputs. They are intentionally hard-coded here so
 * the test asserts byte-for-byte parity with the canonical JS implementation
 * that the Horizon-Wallet extension currently bundles.
 */
const SEED = Uint8Array.from(Array.from({ length: 64 }, (_, i) => i));

const EXPECTED_MASTER_SK =
  "1377f4b2f2479c8f6ea40c3570b7c049cadc4a1cfc8081ebf28e572b80231886";
const EXPECTED_BLS_KEY_MAINNET_0 =
  "600807b7d8e3d8cc9f980aa1937f55ae84dbe540358f026578b84fd231f95f56";
const EXPECTED_BLS_KEY_SIGNET_0 =
  "403ec84ec266cc93809d5a4c576f9b60b44260c739202b857f24d4d47358461b";
const EXPECTED_BLS_KEY_SIGNET_5 =
  "33f336ecc31dab1416993aa03ae859bccc1c18546f95f0ef60e015cf3441f219";
const EXPECTED_BLS_PUB_MAINNET_0 =
  "9251e095439a37075b48b3fca3f63b53134743456646f5173f63b765d93164824f08b722b4339a7eab55c614548751dc178b7b2a7ac21829dfbd95b72620d9ebfa423c15966b4d07a25e4dde4091f229f2dadc1db8c48a9da7536da86db77aa5";
const EXPECTED_BLS_PUB_SIGNET_0 =
  "a56dd059afccd191121b9bb8ec2ff6b9b18e302064e18faca45b6e1b38eb7c7f37130d01ead92037459663c4ff9be3d8198223658e0a0196af2fe68de58cbce9e0299c76e6ec5223791344f3bbda528b7b81dea5fd55b204027d54fa242fdcec";

const EXPECTED_SIGN_AABBCCDD_DEFAULT_DST =
  "b1ec7ccc407fa4ad88548f2348dd9176d514da830bc90b05b245a6f1fe61cf1dbaf466251735230eeab9660f645c6e24";
const EXPECTED_SIGN_AABBCCDD_CUSTOM_DST =
  "a72b8140c308ef31f8d48653c3a6caa87077f9efce112bf3f73dac08c1d36f768f22727e099a2e0cf706ea70a440eed6";
const EXPECTED_SIGN_HELLO_HEX_DEFAULT =
  "8c598f4cb5c9efd80e18c4bacbe671f55df8f0e98070ceb9c140ba2320d7118a26b576edb81135972b8cce6e87a8a0ee";

const X_ONLY_HEX_AA = "aa".repeat(32);
const EXPECTED_BLS_BINDING_SIG_AA =
  "8cb2b5898fca3669e6048e7d5eab06d6aed1f186400bff876bbcaf54c6f930277bc9e08c52234c03b98e7c837e86142b";
const EXPECTED_SCHNORR_BINDING_HASH_PUB_MAIN =
  "5277d920539e71cb09b4bcd9b09d79f3881c38428207b5908a717e88fad0b88d";

const EXPECTED_MASTER_SK_EMPTY =
  "4c67e3512877eb063003bea7429ac36ce032b74f5afe83b202e2bdc3298feee1";

describe("bls-primitives", () => {
  describe("KONTOR_BLS_DST", () => {
    it("re-exports the constant from postcard.ts", () => {
      expect(KONTOR_BLS_DST).toBe("BLS_SIG_BLS12381G1_XMD:SHA-256_SSWU_RO_NUL_");
    });
  });

  describe("deriveMasterSK", () => {
    it("matches Horizon-Wallet vector for the standard 64-byte seed", () => {
      expect(bytesToHex(deriveMasterSK(SEED))).toBe(EXPECTED_MASTER_SK);
    });

    it("returns 32 bytes", () => {
      expect(deriveMasterSK(SEED).length).toBe(32);
    });

    it("matches Horizon-Wallet vector for an empty IKM", () => {
      expect(bytesToHex(deriveMasterSK(new Uint8Array(0)))).toBe(
        EXPECTED_MASTER_SK_EMPTY,
      );
    });
  });

  describe("deriveBlsKey", () => {
    it("matches Horizon vector for mainnet (coinType=0, account=0)", () => {
      expect(bytesToHex(deriveBlsKey(SEED, 0, 0))).toBe(
        EXPECTED_BLS_KEY_MAINNET_0,
      );
    });

    it("matches Horizon vector for signet/testnet (coinType=1, account=0)", () => {
      expect(bytesToHex(deriveBlsKey(SEED, 1, 0))).toBe(
        EXPECTED_BLS_KEY_SIGNET_0,
      );
    });

    it("matches Horizon vector for non-zero account index", () => {
      expect(bytesToHex(deriveBlsKey(SEED, 1, 5))).toBe(
        EXPECTED_BLS_KEY_SIGNET_5,
      );
    });

    it("returns 32 bytes", () => {
      expect(deriveBlsKey(SEED, 0, 0).length).toBe(32);
    });
  });

  describe("getPublicKey", () => {
    it("matches Horizon vector for mainnet/account 0 BLS key", () => {
      const sk = deriveBlsKey(SEED, 0, 0);
      expect(getPublicKey(sk)).toBe(EXPECTED_BLS_PUB_MAINNET_0);
    });

    it("matches Horizon vector for signet/account 0 BLS key", () => {
      const sk = deriveBlsKey(SEED, 1, 0);
      expect(getPublicKey(sk)).toBe(EXPECTED_BLS_PUB_SIGNET_0);
    });

    it("returns 96-byte (192-char hex) compressed G2 point", () => {
      const sk = deriveBlsKey(SEED, 0, 0);
      const pub = getPublicKey(sk);
      expect(pub.length).toBe(192);
    });
  });

  describe("sign", () => {
    it("matches Horizon vector for hex message under default DST", () => {
      const sk = deriveBlsKey(SEED, 0, 0);
      expect(sign("aabbccdd", sk)).toBe(EXPECTED_SIGN_AABBCCDD_DEFAULT_DST);
    });

    it("matches Horizon vector for a custom DST", () => {
      const sk = deriveBlsKey(SEED, 0, 0);
      expect(sign("aabbccdd", sk, "CUSTOM_DST")).toBe(
        EXPECTED_SIGN_AABBCCDD_CUSTOM_DST,
      );
    });

    it("treats undefined dst the same as KONTOR_BLS_DST", () => {
      const sk = deriveBlsKey(SEED, 0, 0);
      expect(sign("aabbccdd", sk)).toBe(sign("aabbccdd", sk, KONTOR_BLS_DST));
    });

    it("hex-encoded UTF-8 'hello' matches Horizon vector", () => {
      const sk = deriveBlsKey(SEED, 0, 0);
      const hex = bytesToHex(new TextEncoder().encode("hello"));
      expect(sign(hex, sk)).toBe(EXPECTED_SIGN_HELLO_HEX_DEFAULT);
    });

    it("signature verifies via @noble/curves shortSignatures.verify", () => {
      const sk = deriveBlsKey(SEED, 0, 0);
      const sigHex = sign("aabbccdd", sk);
      const sigPoint = bls12_381.shortSignatures.Signature.fromHex(sigHex);
      const pubPoint = bls12_381.shortSignatures.getPublicKey(sk);
      const hashed = bls12_381.shortSignatures.hash(
        hexToBytes("aabbccdd"),
        KONTOR_BLS_DST,
      );
      expect(bls12_381.shortSignatures.verify(sigPoint, hashed, pubPoint)).toBe(
        true,
      );
    });
  });

  describe("signBlsBinding", () => {
    it("matches Horizon vector for the standard x-only key", () => {
      const sk = deriveBlsKey(SEED, 0, 0);
      expect(signBlsBinding(sk, X_ONLY_HEX_AA)).toBe(
        EXPECTED_BLS_BINDING_SIG_AA,
      );
    });

    it("returns a 96-character hex string (48 bytes — G1 compressed)", () => {
      const sk = deriveBlsKey(SEED, 0, 0);
      expect(signBlsBinding(sk, X_ONLY_HEX_AA).length).toBe(96);
    });

    it("binding signature verifies under KONTOR_BLS_DST with the prefixed message", () => {
      const sk = deriveBlsKey(SEED, 0, 0);
      const sigHex = signBlsBinding(sk, X_ONLY_HEX_AA);
      const sigPoint = bls12_381.shortSignatures.Signature.fromHex(sigHex);
      const pubPoint = bls12_381.shortSignatures.getPublicKey(sk);

      const prefix = new TextEncoder().encode("KONTOR_BLS_TO_XONLY_V1");
      const xOnlyBytes = hexToBytes(X_ONLY_HEX_AA);
      const msg = new Uint8Array(prefix.length + xOnlyBytes.length);
      msg.set(prefix);
      msg.set(xOnlyBytes, prefix.length);
      const hashed = bls12_381.shortSignatures.hash(msg, KONTOR_BLS_DST);
      expect(bls12_381.shortSignatures.verify(sigPoint, hashed, pubPoint)).toBe(
        true,
      );
    });
  });

  describe("schnorrBindingHash", () => {
    it("matches Horizon vector for the mainnet/account-0 BLS pubkey", () => {
      expect(bytesToHex(schnorrBindingHash(EXPECTED_BLS_PUB_MAINNET_0))).toBe(
        EXPECTED_SCHNORR_BINDING_HASH_PUB_MAIN,
      );
    });

    it("returns a 32-byte Uint8Array", () => {
      const out = schnorrBindingHash(EXPECTED_BLS_PUB_MAINNET_0);
      expect(out).toBeInstanceOf(Uint8Array);
      expect(out.length).toBe(32);
    });

    it("equals sha256(SCHNORR_BINDING_PREFIX || blsPubkeyBytes)", () => {
      const prefix = new TextEncoder().encode("KONTOR_XONLY_TO_BLS_V1");
      const pubBytes = hexToBytes(EXPECTED_BLS_PUB_MAINNET_0);
      const preimage = new Uint8Array(prefix.length + pubBytes.length);
      preimage.set(prefix);
      preimage.set(pubBytes, prefix.length);
      expect(bytesToHex(schnorrBindingHash(EXPECTED_BLS_PUB_MAINNET_0))).toBe(
        bytesToHex(sha256(preimage)),
      );
    });
  });
});
